### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by bastien70** [Lustmored/flysystem-v2-simple-cache-adapter#1]
Hello, I would like to integrate your adapter into my Symfony project to combine it with FlySystem and LiipImagineBundle. But I don't understand how to use your adapter?

**Comment by Lustmored** [comment]
Hi,

In Symfony with flysystem-bundle you'd just need to configure the service like this:
```
flysystem.cache.adapter:
        class: Lustmored\Flysystem\Cache\CacheAdapter
        arguments:
                $adapter: '@flysystem.adapter.public.storage.source'
                $cachePool: '@flysystem.public'
```

And then use it in `config/packages/flysystem.yaml` like any other:
```
public.storage:
        adapter: 'flysystem.cache.adapter'
```

**Comment by bastien70** [comment]
I have a little trouble understanding.

Basically, my setup is as follows:

**flysystem.yaml :**

```yaml
flysystem:
    storages:
        uploads_adapter:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
```

**services.yaml**:

```yaml
Aws\S3\S3Client:
        arguments:
            -   version: '2006-03-01'
                region: "%env(AWS_S3_REGION)%"
                credentials:
                    key: "%env(AWS_S3_ACCESS_ID)%"
                    secret: "%env(AWS_S3_ACCESS_SECRET)%"
```

**liip_imagine.yaml**:
```yaml
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: uploads_adapter

    # Default loader to use for all filter sets
    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: uploads_adapter
                root_url: '%uploads_base_url%'
                cache_prefix: media/cache

    cache: flysystem_resolver
```


So, if I understand, I should make this : 

Add in **services.yaml** : 
```yaml
flysystem.cache.adapter:
        class: Lustmored\Flysystem\Cache\CacheAdapter
        arguments:
                $adapter: '@flysystem.adapter.public.storage.source'
                $cachePool: '@flysystem.public'
```

And add in **flysystem.yaml** : 

```yaml
flysystem.cache.adapter:
        class: Lustmored\Flysystem\Cache\CacheAdapter
        arguments:
                $adapter: '@flysystem.adapter.public.storage.source'
                $cachePool: '@flysystem.public'
```

? What about my other adapt regarding aws? And for the cache to be effective with liip_imagine?

**Comment by weaverryan** [comment]
Hi there!

To adapt the code from @Lustmored to your app, I think it would look like this:

1) Setup a cache pool

```yaml
# config/packages/cache.yaml
framework:
    cache:
        pools:
            cache.flysystem.psr6:
                adapter: cache.app
```

(this is the same that we have here: https://symfonycasts.com/screencast/symfony-uploads/cached-s3-filesystem#codeblock-1a69ab8273

2) Define a cache adapter. The key thing here is that you need to point it to the REAL adapter that you want this to use, in case there is nothing in the cache yet. In your case, it looks like you're using https://github.com/thephpleague/flysystem-bundle to define you "storages", which I believe means you will have a service with the id `flysystem.adapter.uploads_adapter`, which is your adapter service. So:

```yaml
# config/services.yaml
services:
    # ...

    flysystem.cache.adapter:
        class: Lustmored\Flysystem\Cache\CacheAdapter
        arguments:
                $adapter: '@flysystem.adapter.uploads_adapter'
                $cachePool: '@cache.flysystem.psr6'
```

3) At this point, you have a cache adapter. But you need a Filesystem that USES that adapter. Since you're using the PHPLeague package, I think it would look like this:

```yaml
# config/packages/flysystem.yaml
flysystem:
    storages:
        # ... your other storages

        cached_public_uploads_storage:
            # point this at your service id from above
            adapter: 'flysystem.cache.adapter'
```

4) Finally, the above should give you a service id called exactly `cached_public_uploads_storage` I believe. You can now plug this into Liip:

```yaml
liip_imagine:
    # ...
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: cached_public_uploads_storage

    # ...

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: cached_public_uploads_storage
                # ....
```

Yes, it IS complex :). This probably won't be quite right - I was reading from source code and typing here, but it should be close.

Cheers!
